GameData = {["save_version"] = 1, ["language"] = 1, ["network"] = 7, ["networkMax"] = 7, ["overflow"] = 21, ["seed"] = 979832553, ["new_enemies"] = 1, ["new_missions"] = 1, ["new_equip"] = 1, ["difficulty"] = 0, ["new_abilities"] = 1, ["ach_info"] = {["squad"] = "Rust_A", ["trackers"] = {["Detritus_B_2"] = 0, ["Global_Challenge_Power"] = 0, ["Archive_A_1"] = 0, ["Archive_B_2"] = 0, ["Rust_A_2"] = 3, ["Rust_A_3"] = 2, ["Pinnacle_A_3"] = 0, ["Archive_B_1"] = 0, ["Pinnacle_B_3"] = 0, ["Detritus_B_1"] = 0, ["Pinnacle_B_1"] = 0, ["Global_Island_Mechs"] = 3, ["Global_Island_Building"] = 0, ["Squad_Mist_1"] = 0, ["Squad_Bomber_2"] = 0, ["Squad_Spiders_1"] = 0, ["Squad_Mist_2"] = 0, ["Squad_Heat_1"] = 0, ["Squad_Cataclysm_1"] = 0, ["Squad_Cataclysm_2"] = 0, ["Squad_Cataclysm_3"] = 0, },
},


["current"] = {["score"] = 9715, ["time"] = 47567108.000000, ["kills"] = 148, ["damage"] = 0, ["failures"] = 5, ["difficulty"] = 0, ["victory"] = false, ["islands"] = 4, ["squad"] = 1, 
["mechs"] = {"JetMech", "RocketMech", "PulseMech", },
["colors"] = {1, 1, 1, },
["weapons"] = {"Brute_Jetmech", "Passive_FlameImmune", "Ranged_Rocket_A", "Passive_Electric_A", "Science_Repulse_A", "", },
["pilot0"] = {["id"] = "Pilot_Original", ["name"] = "Ralph Karlsson", ["name_id"] = "Pilot_Original_Name", ["renamed"] = false, ["skill1"] = 1, ["skill2"] = 0, ["exp"] = 50, ["level"] = 2, ["travel"] = 3, ["final"] = 3, ["starting"] = true, ["last_end"] = 2, },
["pilot1"] = {["id"] = "Pilot_Detritus", ["name"] = "Zoe Koleda", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 7, ["skill2"] = 8, ["exp"] = 50, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["pilot2"] = {["id"] = "Pilot_Repairman", ["name"] = "Harold Schmidt", ["name_id"] = "Pilot_Repairman_Name", ["renamed"] = false, ["skill1"] = 9, ["skill2"] = 8, ["exp"] = 0, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
},
["current_squad"] = 1, ["undosave"] = true, }
 

RegionData = {
["sector"] = 4, ["island"] = -1, ["secret"] = true, 
["island0"] = {["corporation"] = "Corp_Grass", ["id"] = 0, ["secured"] = true, },
["island1"] = {["corporation"] = "Corp_Desert", ["id"] = 1, ["secured"] = true, },
["island2"] = {["corporation"] = "Corp_Snow", ["id"] = 2, ["secured"] = true, },
["island3"] = {["corporation"] = "Corp_Factory", ["id"] = 3, ["secured"] = true, },
["iBattleRegion"] = 20, 
["final_region"] = {["mission"] = "Mission0", ["player"] = {["battle_type"] = 3, ["iCurrentTurn"] = 4, ["iTeamTurn"] = 1, ["iState"] = 0, ["sMission"] = "Mission0", ["iMissionType"] = 1, ["sBriefingMessage"] = "Final_Mission_Briefing", ["podReward"] = CreateEffect({}), ["secret"] = false, ["spawn_needed"] = false, ["env_time"] = 1000, ["actions"] = 0, ["iUndoTurn"] = 1, ["aiState"] = 3, ["aiDelay"] = 0.000000, ["aiSeed"] = 1296927065, ["victory"] = 2, ["undo_pawns"] = {},


["map_data"] = {["version"] = 7, ["dimensions"] = Point( 8, 8 ), ["name"] = "cave2", ["enemy_kills"] = 8, 
["map"] = {{["loc"] = Point( 0, 0 ), ["terrain"] = 4, },
{["loc"] = Point( 0, 1 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 3 ), ["terrain"] = 0, ["smoke"] = 1, ["smoke"] = 1, },
{["loc"] = Point( 0, 4 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 5 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 0, 6 ), ["terrain"] = 4, },
{["loc"] = Point( 0, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 1, 3 ), ["terrain"] = 0, },
{["loc"] = Point( 1, 5 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 1, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 2, 1 ), ["terrain"] = 0, },
{["loc"] = Point( 2, 2 ), ["terrain"] = 1, ["populated"] = 1, ["smoke"] = 1, ["smoke"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 2, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 3, 3 ), ["terrain"] = 0, },
{["loc"] = Point( 3, 4 ), ["terrain"] = 0, },
{["loc"] = Point( 3, 6 ), ["terrain"] = 0, ["smoke"] = 1, ["smoke"] = 1, },
{["loc"] = Point( 4, 0 ), ["terrain"] = 0, },
{["loc"] = Point( 4, 1 ), ["terrain"] = 0, ["smoke"] = 1, ["smoke"] = 1, },
{["loc"] = Point( 4, 4 ), ["terrain"] = 0, },
{["loc"] = Point( 4, 5 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 4, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 4, 7 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 5, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 5, 2 ), ["terrain"] = 0, ["smoke"] = 1, ["smoke"] = 1, },
{["loc"] = Point( 5, 3 ), ["terrain"] = 0, ["custom"] = "lava_1.png", },
{["loc"] = Point( 5, 5 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 6 ), ["terrain"] = 0, ["smoke"] = 1, ["smoke"] = 1, },
{["loc"] = Point( 6, 0 ), ["terrain"] = 4, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 6, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 6, 3 ), ["terrain"] = 0, ["custom"] = "lava_1.png", },
{["loc"] = Point( 6, 4 ), ["terrain"] = 0, },
{["loc"] = Point( 6, 6 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 6, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 0 ), ["terrain"] = 4, },
{["loc"] = Point( 7, 1 ), ["terrain"] = 4, },
{["loc"] = Point( 7, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 7 ), ["terrain"] = 3, ["lava"] = true, },
},
["cave_tiles"] = {["0"] = {["id"] = "top_L", ["cracked"] = false, ["tentacle"] = false, },
["1"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["2"] = {["id"] = "3", ["cracked"] = true, ["tentacle"] = false, },
["3"] = {["id"] = "1", ["cracked"] = true, ["tentacle"] = false, },
["4"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["5"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = false, },
["6"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["7"] = {["id"] = "end", ["cracked"] = false, ["tentacle"] = false, },
["8"] = {["id"] = "top_R", ["cracked"] = false, ["tentacle"] = false, },
["9"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["10"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["11"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["12"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["13"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["14"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = false, },
["15"] = {["id"] = "end", ["cracked"] = true, ["tentacle"] = false, },
},
["spawns"] = {"Crab2", "Scarab1", },
["spawn_ids"] = {867, 868, },
["spawn_points"] = {Point(5,2), Point(6,2), },
["zones"] = {["pylons"] = {Point( 1, 5 ), Point( 0, 5 ), Point( 4, 5 ), Point( 6, 6 ), Point( 6, 1 ), Point( 5, 1 ), Point( 2, 2 ), },
["mountain"] = {Point( 7, 6 ), Point( 5, 4 ), Point( 1, 7 ), },
["layer"] = {},
["bomb"] = {Point( 2, 4 ), Point( 3, 3 ), },
["deployment"] = {Point( 3, 3 ), Point( 3, 4 ), Point( 2, 4 ), Point( 2, 3 ), },
["enemy"] = {Point( 6, 5 ), Point( 6, 4 ), Point( 5, 5 ), Point( 4, 1 ), Point( 4, 6 ), Point( 5, 2 ), Point( 6, 2 ), Point( 5, 6 ), Point( 3, 0 ), Point( 4, 0 ), Point( 5, 3 ), Point( 4, 7 ), Point( 3, 7 ), Point( 5, 7 ), },
},
["tags"] = {"final_cave", "volcano", },


["pawn1"] = {["type"] = "JetMech", ["name"] = "", ["id"] = 0, ["mech"] = true, ["offset"] = 1, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 1, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {1, },
["primary"] = "Brute_Jetmech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {0, 0, },
["primary_mod2"] = {0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Passive_FlameImmune", ["secondary_power"] = {},
["secondary_power_class"] = false, ["secondary_mod1"] = {0, },
["secondary_mod2"] = {0, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Original", ["name"] = "Ralph Karlsson", ["name_id"] = "Pilot_Original_Name", ["renamed"] = false, ["skill1"] = 1, ["skill2"] = 0, ["exp"] = 50, ["level"] = 2, ["travel"] = 3, ["final"] = 3, ["starting"] = true, ["last_end"] = 2, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 1, ["is_corpse"] = true, ["health"] = 6, ["max_health"] = 6, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(4,0), ["last_location"] = Point(4,2), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 3, ["iMutation"] = 8, ["iOwner"] = 0, ["piTarget"] = Point(4,0), ["piOrigin"] = Point(4,2), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,0), },


["pawn2"] = {["type"] = "RocketMech", ["name"] = "", ["id"] = 1, ["mech"] = true, ["offset"] = 1, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 6, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {1, },
["primary"] = "Ranged_Rocket", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, 1, },
["primary_mod2"] = {0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Passive_Electric", ["secondary_power"] = {},
["secondary_power_class"] = false, ["secondary_mod1"] = {1, 1, 1, },
["secondary_mod2"] = {0, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Detritus", ["name"] = "Zoe Koleda", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 7, ["skill2"] = 8, ["exp"] = 50, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 3, ["is_corpse"] = true, ["health"] = 5, ["max_health"] = 7, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(1,3), ["last_location"] = Point(2,3), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 13, ["iMutation"] = 8, ["iOwner"] = 1, ["piTarget"] = Point(3,3), ["piOrigin"] = Point(1,3), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,3), },


["pawn3"] = {["type"] = "PulseMech", ["name"] = "", ["id"] = 2, ["mech"] = true, ["offset"] = 1, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 3, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {1, },
["healthPower"] = {1, },
["primary"] = "Science_Repulse", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, },
["primary_mod2"] = {0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Repairman", ["name"] = "Harold Schmidt", ["name_id"] = "Pilot_Repairman_Name", ["renamed"] = false, ["skill1"] = 9, ["skill2"] = 8, ["exp"] = 0, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 2, ["is_corpse"] = true, ["bForceField"] = true, ["health"] = 7, ["max_health"] = 7, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(3,3), ["last_location"] = Point(3,2), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 2, ["iMutation"] = 8, ["iOwner"] = 2, ["piTarget"] = Point(3,3), ["piOrigin"] = Point(3,3), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,3), },


["pawn4"] = {["type"] = "Blobber1", ["name"] = "", ["id"] = 765, ["mech"] = false, ["offset"] = 0, ["not_attacking"] = true, ["primary"] = "BlobberAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 3, ["max_health"] = 3, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(6,4), ["last_location"] = Point(6,5), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 765, ["piTarget"] = Point(4,4), ["piOrigin"] = Point(6,4), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,4), },


["pawn5"] = {["type"] = "Firefly1", ["name"] = "", ["id"] = 825, ["mech"] = false, ["offset"] = 0, ["primary"] = "FireflyAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 3, ["max_health"] = 3, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(2,1), ["last_location"] = Point(2,0), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1635020405, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 825, ["piTarget"] = Point(2,2), ["piOrigin"] = Point(2,1), ["piQueuedShot"] = Point(2,2), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(2,2), },


["pawn6"] = {["type"] = "Firefly2", ["name"] = "", ["id"] = 846, ["mech"] = false, ["offset"] = 1, ["primary"] = "FireflyAtk2", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 5, ["max_health"] = 5, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(4,7), ["last_location"] = Point(4,7), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1830959650, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 846, ["piTarget"] = Point(4,6), ["piOrigin"] = Point(4,7), ["piQueuedShot"] = Point(4,6), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,6), },


["pawn7"] = {["type"] = "Jelly_Lava1", ["name"] = "", ["id"] = 847, ["mech"] = false, ["offset"] = 6, ["not_attacking"] = true, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 2, ["max_health"] = 2, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,5), ["last_location"] = Point(5,6), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1830959650, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 847, ["piTarget"] = Point(-2147483647,-2147483647), ["piOrigin"] = Point(5,6), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },


["pawn8"] = {["type"] = "Blob1", ["name"] = "", ["id"] = 866, ["mech"] = false, ["offset"] = 0, ["owner"] = 765, ["primary"] = "BlobAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 1, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(4,4), ["last_location"] = Point(4,4), ["bMinor"] = true, ["iCurrentWeapon"] = 1, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1025531188, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 866, ["piTarget"] = Point(4,4), ["piOrigin"] = Point(4,4), ["piQueuedShot"] = Point(4,4), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,4), },


["pawn9"] = {["type"] = "BigBomb", ["name"] = "", ["id"] = 767, ["mech"] = false, ["offset"] = 0, ["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 3, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(3,4), ["last_location"] = Point(-1,-1), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iMutation"] = 8, ["iOwner"] = 767, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },
["pawn_count"] = 9, ["blocked_points"] = {Point(0,5), Point(1,5), Point(2,2), Point(4,5), Point(5,1), Point(6,1), Point(6,6), },
["blocked_type"] = {2, 2, 2, 2, 2, 2, 2, },
},


},
["state"] = 1, ["name"] = "Volcanic Hive", },
}
 

GAME = { 
["WeaponDeck"] = { 
[31] = "Ranged_Fireball", 
[2] = "Prime_Lightning", 
[8] = "Prime_Areablast", 
[32] = "Ranged_RainingVolley", 
[33] = "Ranged_Wide", 
[34] = "Science_Pullmech", 
[35] = "Science_Gravwell", 
[9] = "Prime_Leap", 
[36] = "Science_Swap", 
[37] = "Science_AcidShot", 
[38] = "Science_Confuse", 
[39] = "Science_SmokeDefense", 
[10] = "Prime_Sword", 
[40] = "Science_Shield", 
[41] = "Science_FreezeBeam", 
[42] = "Science_LocalShield", 
[43] = "Science_PushBeam", 
[11] = "Prime_Smash", 
[44] = "Support_Boosters", 
[45] = "Support_Refrigerate", 
[46] = "Support_Destruct", 
[3] = "Prime_Lasermech", 
[12] = "Brute_Tankmech", 
[48] = "DeploySkill_Tank", 
[49] = "DeploySkill_PullTank", 
[50] = "Support_Force", 
[51] = "Support_SmokeDrop", 
[13] = "Brute_PhaseShot", 
[52] = "Support_Repair", 
[53] = "Support_Missiles", 
[54] = "Support_Wind", 
[55] = "Support_Blizzard", 
[14] = "Brute_Grapple", 
[56] = "Passive_Leech", 
[57] = "Passive_MassRepair", 
[58] = "Passive_Defenses", 
[59] = "Passive_Burrows", 
[15] = "Brute_Shrapnel", 
[60] = "Passive_AutoShields", 
[61] = "Passive_Boosters", 
[62] = "Passive_Medical", 
[1] = "Prime_Punchmech", 
[4] = "Prime_Rockmech", 
[16] = "Brute_Sniper", 
[64] = "Passive_CritDefense", 
[65] = "Prime_Flamespreader", 
[66] = "Prime_WayTooBig", 
[17] = "Brute_Shockblast", 
[68] = "Prime_TC_Feint", 
[69] = "Prime_KO_Crack", 
[70] = "Brute_KickBack", 
[18] = "Brute_Beetle", 
[72] = "Brute_TC_GuidedMissile", 
[73] = "Brute_TC_Ricochet", 
[74] = "Brute_TC_DoubleShot", 
[19] = "Brute_Heavyrocket", 
[76] = "Ranged_Crack", 
[77] = "Ranged_DeployBomb", 
[5] = "Prime_RightHook", 
[20] = "Brute_Splitshot", 
[80] = "Ranged_TC_BounceShot", 
[81] = "Ranged_TC_DoubleArt", 
[82] = "Ranged_KO_Combo", 
[21] = "Brute_Bombrun", 
[84] = "Science_MassShift", 
[85] = "Science_TelePush", 
[86] = "Science_TC_Control", 
[22] = "Brute_Sonic", 
[88] = "Science_KO_Crack", 
[89] = "Support_Confuse", 
[90] = "Support_GridDefense", 
[23] = "Ranged_Artillerymech", 
[92] = "Support_TC_GridAtk", 
[93] = "Support_TC_Bombline", 
[6] = "Prime_Shift", 
[24] = "Ranged_Rockthrow", 
[96] = "Passive_FireBoost", 
[97] = "Passive_PlayerTurnShield", 
[98] = "Passive_VoidShock", 
[25] = "Ranged_Defensestrike", 
[26] = "Ranged_Ignite", 
[47] = "DeploySkill_ShieldTank", 
[63] = "Passive_FriendlyFire", 
[27] = "Ranged_ScatterShot", 
[91] = "Support_Waterdrill", 
[67] = "Prime_PrismLaser", 
[7] = "Prime_Flamethrower", 
[28] = "Ranged_BackShot", 
[71] = "Brute_PierceShot", 
[75] = "Brute_KO_Combo", 
[78] = "Ranged_Arachnoid", 
[29] = "Ranged_Ice", 
[79] = "Ranged_SmokeFire", 
[83] = "Science_RainingFire", 
[87] = "Science_TC_SwapOther", 
[30] = "Ranged_SmokeBlast", 
[94] = "Support_KO_GridCharger", 
[95] = "Passive_HealingSmoke" 
}, 
["PodWeaponDeck"] = { 
[27] = "Support_Force", 
[2] = "Prime_Leap", 
[38] = "Passive_Boosters", 
[3] = "Prime_Sword", 
[54] = "Support_TC_GridAtk", 
[4] = "Prime_Smash", 
[5] = "Brute_Grapple", 
[6] = "Brute_Sniper", 
[7] = "Brute_Shockblast", 
[8] = "Brute_Beetle", 
[10] = "Brute_Bombrun", 
[12] = "Ranged_Ice", 
[14] = "Ranged_Fireball", 
[16] = "Science_SmokeDefense", 
[20] = "Science_PushBeam", 
[24] = "DeploySkill_ShieldTank", 
[28] = "Support_SmokeDrop", 
[32] = "Support_Blizzard", 
[40] = "Passive_FriendlyFire", 
[48] = "Ranged_TC_DoubleArt", 
[56] = "Support_KO_GridCharger", 
[33] = "Passive_Leech", 
[41] = "Passive_CritDefense", 
[49] = "Ranged_KO_Combo", 
[57] = "Passive_HealingSmoke", 
[17] = "Science_Shield", 
[21] = "Support_Boosters", 
[25] = "DeploySkill_Tank", 
[29] = "Support_Repair", 
[34] = "Passive_MassRepair", 
[42] = "Prime_WayTooBig", 
[50] = "Science_TelePush", 
[58] = "Passive_FireBoost", 
[31] = "Support_Wind", 
[9] = "Brute_Heavyrocket", 
[13] = "Ranged_SmokeBlast", 
[15] = "Ranged_RainingVolley", 
[35] = "Passive_Defenses", 
[11] = "Brute_Sonic", 
[51] = "Support_Confuse", 
[59] = "Passive_PlayerTurnShield", 
[18] = "Science_FreezeBeam", 
[22] = "Support_Refrigerate", 
[26] = "DeploySkill_PullTank", 
[30] = "Support_Missiles", 
[36] = "Passive_Burrows", 
[44] = "Prime_TC_Feint", 
[52] = "Support_GridDefense", 
[60] = "Passive_VoidShock", 
[47] = "Ranged_TC_BounceShot", 
[46] = "Brute_KO_Combo", 
[39] = "Passive_Medical", 
[43] = "Prime_PrismLaser", 
[37] = "Passive_AutoShields", 
[45] = "Brute_TC_GuidedMissile", 
[53] = "Support_Waterdrill", 
[1] = "Prime_Areablast", 
[19] = "Science_LocalShield", 
[23] = "Support_Destruct", 
[55] = "Support_TC_Bombline" 
}, 
["PilotDeck"] = { 
[7] = "Pilot_Leader", 
[1] = "Pilot_Soldier", 
[2] = "Pilot_Youth", 
[4] = "Pilot_Aquatic", 
[8] = "Pilot_Caretaker", 
[9] = "Pilot_Chemical", 
[5] = "Pilot_Medic", 
[10] = "Pilot_Delusional", 
[3] = "Pilot_Warrior", 
[6] = "Pilot_Miner" 
}, 
["SeenPilots"] = { 
[7] = "Pilot_Arrogant", 
[1] = "Pilot_Original", 
[2] = "Pilot_Detritus", 
[4] = "Pilot_Hotshot", 
[8] = "Pilot_Genius", 
[9] = "Pilot_Assassin", 
[5] = "Pilot_Repairman", 
[3] = "Pilot_Rust", 
[6] = "Pilot_Recycler" 
}, 
["PodDeck"] = { 
[1] = { 
["cores"] = 1 
}, 
[2] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[4] = { 
["cores"] = 1, 
["pilot"] = "random" 
}, 
[3] = { 
["cores"] = 1, 
["weapon"] = "random" 
} 
}, 
["Bosses"] = { 
[1] = "Mission_HornetBoss", 
[2] = "Mission_BouncerBoss", 
[4] = "Mission_ScorpionBoss", 
[3] = "Mission_BurnbugBoss" 
}, 
["Island"] = 4, 
["Missions"] = { 
[0] = { 
["Spawner"] = { 
["num_spawns"] = 11, 
["used_bosses"] = 0, 
["spawn_island"] = 5, 
["curr_weakRatio"] = { 
[1] = 3, 
[2] = 4 
}, 
["curr_upgradeRatio"] = { 
[1] = 2, 
[2] = 4 
}, 
["upgrade_streak"] = 0, 
["num_bosses"] = 0, 
["pawn_counts"] = { 
["Crab"] = 1, 
["Scarab"] = 1, 
["Jelly_Lava"] = 1, 
["Hornet"] = 3, 
["Firefly"] = 3, 
["Scorpion"] = 3, 
["Leaper"] = 2, 
["Blobber"] = 1 
} 
}, 
["LiveEnvironment"] = { 
["Locations"] = { 
[1] = Point( 7, 3 ), 
[2] = Point( 6, 3 ), 
[3] = Point( 5, 3 ), 
[4] = Point( 4, 3 ), 
[5] = Point( 3, 3 ), 
[6] = Point( 2, 3 ), 
[7] = Point( 1, 3 ), 
[8] = Point( 0, 3 ) 
}, 
["LavaPath"] = { 
[1] = Point( 7, 5 ), 
[2] = Point( 6, 5 ), 
[3] = Point( 5, 5 ), 
[4] = Point( 4, 5 ), 
[5] = Point( 3, 5 ), 
[6] = Point( 2, 5 ), 
[7] = Point( 1, 5 ), 
[8] = Point( 0, 5 ) 
}, 
["Instant"] = true, 
["EndEffect"] = true, 
["Planned"] = { 
[1] = Point( 7, 3 ), 
[2] = Point( 6, 3 ), 
[3] = Point( 5, 3 ), 
[4] = Point( 4, 3 ), 
[5] = Point( 3, 3 ), 
[6] = Point( 2, 3 ), 
[7] = Point( 1, 3 ), 
[8] = Point( 0, 3 ) 
}, 
["Phase"] = 4, 
["Mode"] = 2, 
["StartEffect"] = true, 
["WaterTarget"] = false 
}, 
["ID"] = "Mission_Final_Cave", 
["VoiceEvents"] = { 
}, 
["BonusObjs"] = { 
} 
} 
}, 
["Enemies"] = { 
[1] = { 
[6] = "Shaman", 
[2] = "Mosquito", 
[3] = "Firefly", 
[1] = "Leaper", 
[4] = "Jelly_Armor", 
[5] = "Crab", 
["island"] = 1 
}, 
[2] = { 
[6] = "Beetle", 
[2] = "Hornet", 
[3] = "Scarab", 
[1] = "Scorpion", 
[4] = "Jelly_Health", 
[5] = "Dung", 
["island"] = 2 
}, 
[4] = { 
[6] = "Spider", 
[2] = "Bouncer", 
[3] = "Firefly", 
[1] = "Leaper", 
[4] = "Jelly_Fire", 
[5] = "Centipede", 
["island"] = 4 
}, 
[3] = { 
[6] = "Blobber", 
[2] = "Moth", 
[3] = "Bouncer", 
[1] = "Burnbug", 
[4] = "Jelly_Regen", 
[5] = "Digger", 
["island"] = 3 
} 
} 
}

 

SquadData = {
["money"] = 0, ["cores"] = 0, ["bIsFavor"] = false, ["repairs"] = 0, ["CorpReward"] = {CreateEffect({weapon = "Science_TC_Enrage",}), CreateEffect({skill1 = "Invulnerable",skill2 = "Closer",pilot = "Pilot_Genius",}), CreateEffect({power = 2,}), },
["RewardClaimed"] = true, 
["skip_pawns"] = true, 

["storage_size"] = 6, ["storage_3"] = {["pilot"] = true, ["id"] = "Pilot_Recycler", ["name"] = "Prospero", ["name_id"] = "Pilot_Recycler_Name", ["renamed"] = false, ["skill1"] = 8, ["skill2"] = 1, ["exp"] = 3, ["level"] = 1, ["travel"] = 0, ["final"] = 0, ["starting"] = false, ["power"] = {0, },
},
["storage_4"] = {["weapon"] = "Prime_TC_BendBeam", },
["storage_5"] = {["pilot"] = true, ["id"] = "Pilot_Assassin", ["name"] = "Abe Isamu", ["name_id"] = "Pilot_Assassin_Name", ["renamed"] = false, ["skill1"] = 6, ["skill2"] = 11, ["exp"] = 33, ["level"] = 1, ["travel"] = 0, ["final"] = 0, ["starting"] = false, },
["CorpStore"] = {CreateEffect({weapon = "Brute_Unstable",money = -2,}), CreateEffect({weapon = "Brute_Mirrorshot",money = -2,}), CreateEffect({weapon = "Prime_TC_Punt",money = -2,}), CreateEffect({weapon = "Support_Smoke",money = -2,}), CreateEffect({money = -3,stock = -1,cores = 1,}), CreateEffect({money = -1,power = 1,stock = -1,}), },
["island_store_count"] = 3, ["store_undo_size"] = 3, ["store_undo_0"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
["store_undo_1"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
["store_undo_2"] = {["Effect"] = CreateEffect({money = 3,stock = -1,cores = -1,}), },
}
 

