"""Squad-aware mission picker.

Layer-4 (Strategist) component. Given a squad's current weapons and an
``island_map`` payload from the bridge, scores each available mission
and returns a ranked recommendation list with rationale lines.

Pipeline:
    bridge state.island_map  --(score_island_map)-->  ranked list
    bridge state.units(mechs) --(derive_squad_tags)-->  set of tags

Scoring is intentionally simple and additive so rationales are easy to
read: ``total = sum(bonus_value, ...) + sum(penalty, ...)``. Bonus
values reward objectives we're likely to hit; penalties express
mission/squad-mismatch and grid-state hazards. Tweak the constants in
``score_mission`` rather than refactoring the structure.

Concrete failure this addresses (run 20260425_185532_218 m04→m05):
    A Lightning/Jet/Grav-Well squad on Detritus took Historic County
    (a train mission with High Threat ⚡) without a train_defender
    mech, lost a pilot, then wiped on Secondary Archives ("do not
    kill Volatile Vek") with no crowd-control. The picker here would
    have ranked Historic County far below alternatives because of
    `train` + `no train_defender` (-8) and `high_threat` + grid<5
    (-5), and Secondary Archives below alternatives because of
    `volatile_vek` + `no crowd_control` (-3).

Mission metadata source-of-truth:
    ``data/mission_metadata.json`` (generated by
    ``scripts/extract_mission_metadata.py`` from the game's
    ``missions/*.lua``). When that file is present, mission tags are
    derived from its authoritative ``forced_pawns`` /
    ``boss_pawn`` / ``boss_list`` / ``environment`` / ``train_mission``
    / ``boss_mission`` fields. The legacy ``MISSION_ID_TAGS`` substring
    table is still consulted as a fallback for missions the metadata
    doesn't know about (mods, beta builds).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# ----------------------------------------------------------------------
# BONUS objective enum (mirrors scripts/missions/missions.lua:32-40).
# Lua-side BonusObjs is a list of these int values.
# ----------------------------------------------------------------------
BONUS_ASSET = 1        # Save AssetId building (varies; pilot pod / corp asset)
BONUS_KILL = 2         # Kill all (deprecated; rarely surfaces)
BONUS_GRID = 3         # ⚡ Don't lose more than N grid power (defensive)
BONUS_MECHS = 4        # ★ Don't let any mech die
BONUS_BLOCK = 5        # Block emergence
BONUS_KILL_FIVE = 6    # Kill at least 7 enemies (Hard difficulty)
BONUS_DEBRIS = 7       # Destroy mountains/buildings to clear debris
BONUS_SELFDAMAGE = 8   # Take no self-damage
BONUS_PACIFIST = 9     # Kill <=N enemies / pacifist-style objective

# Bonus → display symbol used in CLI rationale lines.
BONUS_SYMBOL = {
    BONUS_ASSET: "⊕",
    BONUS_KILL: "★",
    BONUS_GRID: "⚡",
    BONUS_MECHS: "★",
    BONUS_BLOCK: "★",
    BONUS_KILL_FIVE: "★",
    BONUS_DEBRIS: "★",
    BONUS_SELFDAMAGE: "★",
    BONUS_PACIFIST: "★",
}

# ----------------------------------------------------------------------
# Squad weapon → capability tags. Bridge unit.weapons is a list of Lua
# weapon ids (e.g. "Prime_Lightning", "Science_Gravwell"). Each id maps
# to zero or more tags. Add new ids here as they appear in squads.
#
# Tag semantics:
#   burst         — multi-hit; useful for "kill 7" bonuses
#   aoe           — multi-tile damage (artillery splash, beam, etc.)
#   armor_pierce  — bypasses Armor (Burst Beam, Lightning chain)
#   flying        — passive that lets the mech fly (water/chasm immunity)
#   train_defender — can reliably stop or escort the train
#                    (push-source within 1-2 tiles of any column —
#                    melee/dash with reliable single-target push, OR
#                    pull-source like Grappling Hook)
#   crowd_control — can disable a Vek without killing it (freeze, web,
#                   smoke, push-into-mountain, swap, repulse). Critical
#                   for "do not kill X" missions where you must defend
#                   the protected enemy.
#   repair        — heals adjacent / self (Mass Repair, etc.)
#   push_chain    — multi-target push (Repulse, Vulcan adjacent,
#                   Cluster, Gravity Well)
#   walking_bomb_deploy — creates Walking Bomb bodies for Bombermechs
#                         death-count achievements
# ----------------------------------------------------------------------
WEAPON_TAGS: dict[str, list[str]] = {
    # PRIME — single-target melee w/ push (good train defenders)
    "Prime_Punchmech":   ["train_defender"],          # Titan Fist
    "Prime_Lightning":   ["aoe", "armor_pierce", "burst"],  # multi-target chain
    "Prime_Lasermech":   ["aoe", "armor_pierce"],     # piercing line
    "Prime_ShieldBash":  ["train_defender"],
    "Prime_Shift":       ["crowd_control"],           # forced-move
    "Prime_Flamethrower": ["push_chain", "burst"],    # fire spreads
    "Prime_Areablast":   ["aoe", "push_chain"],
    "Prime_Leap":        ["aoe"],
    "Prime_Spear":       ["aoe", "armor_pierce"],
    "Prime_RocketPunch": ["train_defender"],
    "Prime_RightHook":   ["train_defender"],
    "Prime_SpinFist":    ["push_chain"],
    "Prime_Sword":       ["aoe", "burst"],
    "Prime_Smash":       ["train_defender", "aoe"],
    # Cataclysm squad.
    "Prime_TC_Punt":     ["cataclysm_chasm"],        # Hydraulic Lifter
    "Prime_TC_Punt_A":   ["cataclysm_chasm"],
    "Prime_TC_Punt_B":   ["cataclysm_chasm"],
    "Prime_TC_Punt_AB":  ["cataclysm_chasm"],
    # BRUTE — ranged / dash
    "Brute_Tankmech":    ["train_defender"],          # Taurus Cannon (push)
    "Brute_Jetmech":     ["aoe", "burst", "flying"],  # Aerial Bombs
    "Brute_Mirrorshot":  ["aoe"],
    "Brute_Beetle":      ["train_defender"],
    "Brute_Grapple":     ["train_defender", "crowd_control"],  # pull
    "Brute_Heavyrocket": ["aoe", "burst"],
    "Brute_Sonic":       ["push_chain"],
    "Brute_Shockblast":  ["aoe", "push_chain"],
    "Brute_Sniper":      ["armor_pierce"],
    "Brute_Splitshot":   ["burst"],
    "Brute_Bombrun":     ["aoe", "burst"],
    "Brute_PhaseShot":   ["armor_pierce"],
    "Brute_PierceShot":  ["aoe", "armor_pierce", "burst"],
    "Brute_PierceShot_A": ["aoe", "armor_pierce", "burst"],
    "Brute_PierceShot_B": ["aoe", "armor_pierce", "burst"],
    "Brute_PierceShot_AB": ["aoe", "armor_pierce", "burst"],
    "Brute_Shrapnel":    ["aoe"],
    # RANGED — artillery
    "Ranged_Artillerymech": ["aoe", "push_chain"],    # Artemis Artillery
    "Ranged_Rocket":     ["aoe", "burst"],            # Rocket Artillery
    "Ranged_Rockthrow":  ["aoe", "push_chain"],
    "Ranged_Defensestrike": ["aoe"],
    "Ranged_Ignite":     ["aoe", "burst"],
    "Ranged_Ice":        ["crowd_control"],           # freeze
    "Ranged_ScatterShot": ["aoe", "burst"],
    "Ranged_BackShot":   ["aoe"],
    "Ranged_Wide":       ["aoe", "burst"],
    "Ranged_Crack":      ["cataclysm_chasm", "aoe"], # Tri-Rocket
    "Ranged_Crack_A":    ["cataclysm_chasm", "aoe"],
    "Ranged_Crack_B":    ["cataclysm_chasm", "aoe"],
    "Ranged_Crack_AB":   ["cataclysm_chasm", "aoe"],
    "Ranged_DeployBomb": ["walking_bomb_deploy", "no_survivors_setup"],
    "Ranged_DeployBomb_A": ["walking_bomb_deploy", "no_survivors_setup"],
    "Ranged_DeployBomb_B": ["walking_bomb_deploy", "no_survivors_setup"],
    "Ranged_DeployBomb_AB": ["walking_bomb_deploy", "no_survivors_setup"],
    # SCIENCE — utility
    "Science_Pullmech":  ["crowd_control", "train_defender"],
    "Science_Gravwell":  ["crowd_control"],           # pull artillery
    "Science_Repulse":   ["push_chain", "crowd_control"],
    "Science_Swap":      ["crowd_control"],           # teleport swap
    "Science_AcidShot":  ["crowd_control"],           # ACID
    "Science_Shield":    ["repair"],                  # shield as defense
    "Science_Confuse":   ["crowd_control"],
    "Science_KO_Crack":  ["cataclysm_chasm"],        # Seismic Capacitor
    "Science_KO_Crack_A": ["cataclysm_chasm"],
    "Science_KO_Crack_B": ["cataclysm_chasm"],
    "Science_KO_Crack_AB": ["cataclysm_chasm"],
    "Science_TC_SwapOther": ["crowd_control"],
    "Science_TC_SwapOther_A": ["crowd_control"],
    "Science_TC_SwapOther_B": ["crowd_control"],
    "Science_TC_SwapOther_AB": ["crowd_control"],
    # SUPPORT
    "Support_Repair":    ["repair"],
    "Support_Wind":      ["crowd_control", "push_chain"],
    # PASSIVES
    "Passive_MassRepair": ["repair"],
    "Passive_HealingSmoke": ["repair", "crowd_control"],  # smoke disables Vek
    "Passive_Boosters":  ["flying"],
    "Passive_FlameImmune": [],
    "Passive_FriendlyFire": [],   # *enemy* tag — irrelevant to squad
    "Passive_Defenses":  [],
    "Passive_Electric":  ["aoe"],
}


def derive_squad_tags(units: list[dict[str, Any]]) -> set[str]:
    """Derive capability tags from the live squad's weapons.

    ``units`` is the bridge units list (or any list with `mech: True`
    + `weapons: [str, ...]`). Returns the union of WEAPON_TAGS for
    every weapon id on every living mech.
    """
    tags: set[str] = set()
    for u in units:
        if not u.get("mech"):
            continue
        if u.get("hp", 1) <= 0:
            continue
        for wid in u.get("weapons", []) or []:
            for t in WEAPON_TAGS.get(wid, []):
                tags.add(t)
    return tags


# ----------------------------------------------------------------------
# Mission ID → mission tags. Same idea: substring-match because the
# Lua mission.ID is a stable template name like "Mission_Train",
# "Mission_Volatile", "Mission_Lightning_Mech". New mission IDs land
# here as they're encountered.
# ----------------------------------------------------------------------
MISSION_ID_TAGS: dict[str, list[str]] = {
    # Train missions — must defend a Train_Pawn that walks 2 tiles/turn
    "Mission_Train":          ["train"],
    "Mission_Armored_Train":  ["train"],
    # Volatile Vek — bonus penalises killing a specific glowing Vek
    "Mission_Volatile":       ["volatile_vek"],
    "Mission_VolatileMine":   ["volatile_vek"],
    # Cataclysm / Seismic / Tidal — terrain-conversion env
    "Mission_Lightning_Mech": ["high_threat"],
    "Mission_LightningStorm": ["env_lightning"],
    "Mission_Tidal":          ["env_tidal"],
    "Mission_Cataclysm":      ["env_cataclysm"],
    # Survive / battle
    "Mission_Survive":        ["protect_buildings"],
    "Mission_Battle":         ["high_threat"],
    "Mission_Tanks":          ["fragile_ally_objective"],
    "Mission_Terraform":      ["terraform_grass_counter"],
    "Mission_Filler":         ["earth_mover_pit"],
    "Mission_Holes":          ["mite_counter"],
    "Mission_Dam":            ["mite_counter"],
    "Mission_Teleporter":     ["mite_counter"],
    "Mission_Repair":         ["bad_repairs", "repair_platforms"],
    # Custom Archive objective: "End with 8 spaces on fire". The tactical
    # solver does not hard-gate this counter yet, so it is unsafe for
    # Perfect Island farming even for Flame Behemoths.
    "Mission_ForestFire":     ["fire_tile_counter"],
    # Final / boss
    "Mission_Final":          ["high_threat", "boss"],
    # Critical buildings (Solar / Wind / Power) — protect 2 specific buildings
    "Mission_Solar":          ["protect_specific_building"],
    "Mission_Wind":           ["protect_specific_building"],
    "Mission_Power":          ["protect_specific_building"],
}

# Environment string → mission tags. Lua emits the class name like
# "Env_TidalWaves". Substring match (Env_Lava → tag "env_lava").
ENVIRONMENT_TAGS: dict[str, list[str]] = {
    "Env_Lava":         ["env_lava"],
    "Env_Tidal":        ["env_tidal"],
    "Env_TidalWaves":   ["env_tidal"],
    "Env_Tides":        ["env_tidal"],
    "Env_Terratide":    ["env_tidal"],
    "Env_Conveyor":     ["conveyor"],
    "Env_ConveyorBelt": ["conveyor"],
    "Env_Sandstorm":    ["defensive_smoke"],
    "Env_AirStrike":    ["env_lightning"],
    "Env_Lightning":    ["env_lightning"],
    "Env_LightningStorm": ["env_lightning"],
    "Env_Cataclysm":    ["env_cataclysm"],
    "Env_Seismic":      ["env_cataclysm"],
    "Env_RepairMission": ["bad_repairs", "repair_platforms"],
    # Vanilla Ice Storm. The in-game class is Env_SnowStorm; the display
    # name "Ice Storm" comes from text_missions.lua:162 Env_SnowStorm_Name.
    # The "Env_IceStorm" alias here used to be dead code — it never
    # matched a real LiveEnvironment instance. Removed when the bridge
    # classifier was rewritten in sim v25.
    "Env_SnowStorm":    ["defensive_freeze"],
    # NanoStorm (Detritus Acid variant): not a freeze; 1 damage + ACID.
    "Env_NanoStorm":    ["env_acid"],
    "Env_Wind":         ["env_wind"],
    "Env_Null":         [],
}


# ----------------------------------------------------------------------
# Pawn-id → enemy-class tag. Drives the metadata-derived tags
# ``flier_heavy``, ``armored_heavy``, ``psion_present``. We tag both the
# tier-1 base name (``Hornet``) and any boss/leader/level variants we
# know about (``HornetBoss``, ``Hornet1`` / ``Hornet2``). The substring
# checks below handle suffix variants we don't enumerate explicitly.
# Bestiary source: data/ref_vek_bestiary.md.
# ----------------------------------------------------------------------
FLIER_PAWNS: set[str] = {
    "Hornet", "Hornet1", "Hornet2", "HornetBoss",
    "Firefly", "Firefly1", "Firefly2", "FireflyBoss",
    "Mosquito", "Mosquito1", "Mosquito2",
    "Moth", "Moth1", "Moth2",
}
ARMORED_PAWNS: set[str] = {
    "Beetle", "Beetle1", "Beetle2", "BeetleBoss",
    # Boss/leader variants and Crab/Centipede/Scarab leaders. Any
    # ``*_Leader`` is also caught by the substring rule below.
    "Crab", "CrabBoss",
    "Centipede", "CentipedeBoss",
    "Scarab", "ScarabBoss",
    # Heavy bots in Pinnacle missions
    "BotBoss", "BotBoss2",
}
PSION_PAWN_PREFIX = "Jelly_"   # all Jelly_* variants are psions (incl. Boss)
PSION_PAWNS: set[str] = {"Jelly_Boss"}


def _pawn_is_flier(pawn: str) -> bool:
    if pawn in FLIER_PAWNS:
        return True
    # ``Hornet1`` / ``Hornet2`` / ``HornetBoss`` etc. — substring check.
    for base in ("Hornet", "Firefly", "Mosquito", "Moth"):
        if pawn.startswith(base):
            return True
    return False


def _pawn_is_armored(pawn: str) -> bool:
    if pawn in ARMORED_PAWNS:
        return True
    if pawn.startswith("Beetle"):
        return True
    if pawn.endswith("_Leader"):
        return True
    return False


def _pawn_is_psion(pawn: str) -> bool:
    return pawn.startswith(PSION_PAWN_PREFIX)


# ----------------------------------------------------------------------
# data/mission_metadata.json loader. Lazy-cached; tests can override by
# passing ``mission_metadata`` directly to ``derive_mission_tags`` /
# ``score_mission`` / ``score_island_map``.
# ----------------------------------------------------------------------
_METADATA_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "mission_metadata.json"
)
_METADATA_CACHE: dict[str, dict[str, Any]] | None = None


def load_mission_metadata(
    path: Path | str | None = None,
) -> dict[str, dict[str, Any]]:
    """Return the ``{mission_id: record}`` dict from mission_metadata.json.

    Uses a process-wide cache when ``path`` is ``None``. Returns an empty
    dict if the file is missing — the picker falls back to its
    substring tables in that case.
    """
    global _METADATA_CACHE
    if path is None:
        if _METADATA_CACHE is not None:
            return _METADATA_CACHE
        path = _METADATA_PATH
    p = Path(path)
    if not p.is_file():
        if path == _METADATA_PATH:
            _METADATA_CACHE = {}
        return {}
    payload = json.loads(p.read_text())
    missions = payload.get("missions", {}) if isinstance(payload, dict) else {}
    if path == _METADATA_PATH:
        _METADATA_CACHE = missions
    return missions


def _tags_from_metadata(
    rec: dict[str, Any] | None,
) -> set[str]:
    """Derive the picker tag set from one mission_metadata.json record."""
    tags: set[str] = set()
    if not rec:
        return tags
    if rec.get("train_mission"):
        tags.add("train")
    environment = rec.get("environment")
    if isinstance(environment, str):
        tags.update(ENVIRONMENT_TAGS.get(environment, []))
    if rec.get("turn_limit") == 3:
        tags.add("four_turn")
    if rec.get("boss_mission"):
        tags.add("boss")
        tags.add("high_threat")
    if rec.get("boss_list"):  # Mission_Final / Final_Cave
        tags.add("boss")
        tags.add("high_threat")
    if rec.get("has_objective_building"):
        # Critical missions / Mission_Solar / Wind / Power pin an
        # objective building. Train and boss missions also report
        # has_objective_building but already carry their own dedicated
        # tag (``train`` / ``boss``) that drives more specific penalties
        # — adding ``protect_specific_building`` on top would double-fire.
        if not rec.get("train_mission") and not rec.get("boss_mission"):
            tags.add("protect_specific_building")
    if rec.get("infinite_spawn"):
        # Mission_Infinite descendants spawn a fresh wave every turn
        # (Mission:GetSpawnCount in missions.lua:937; SpawnsPerTurn={2,3}
        # baseline). The implication for the picker: even a *won* mission
        # bleeds grid more than a fixed-roster Mission_Battle of the same
        # nominal star value, because each turn brings new emergence
        # damage opportunities. ~93% of mission templates inherit from
        # Mission_Infinite (only Mission_Battle / Reactivation / Respawn /
        # Test / Tutorial don't), so this tag fires broadly — the
        # corresponding penalty must therefore stay modest, applying
        # only at low grid where the next-mission cliff matters.
        tags.add("infinite_spawn")
    forced = rec.get("forced_pawns") or []
    if "GlowingScorpion" in forced:
        tags.add("volatile_vek")
    # Enemy-class tags from forced_pawns (boss + train units only — for
    # procedural roster we don't have static info, so these tags fire
    # only when the mission *guarantees* the type).
    n_flier = sum(1 for p in forced if _pawn_is_flier(p))
    n_armor = sum(1 for p in forced if _pawn_is_armored(p))
    n_psion = sum(1 for p in forced if _pawn_is_psion(p))
    if n_flier:
        tags.add("flier_heavy")
    if n_armor:
        tags.add("armored_heavy")
    if n_psion:
        tags.add("psion_present")
    return tags


def derive_mission_tags(
    mission_id: str,
    bonus_objective_ids: list[int],
    environment: str | None,
    mission_metadata: dict[str, dict[str, Any]] | None = None,
) -> set[str]:
    """Derive a flat set of mission tags from id + bonus + environment.

    When ``mission_metadata`` is provided (or the on-disk
    ``data/mission_metadata.json`` is loadable), tags derived from the
    authoritative Lua-extracted record take precedence. The legacy
    substring tables remain as fallback.
    """
    tags: set[str] = set()
    if mission_id:
        tags.update(MISSION_ID_TAGS.get(mission_id, []))
    if environment:
        tags.update(ENVIRONMENT_TAGS.get(environment, []))
    # Authoritative metadata overlay.
    md = mission_metadata if mission_metadata is not None else load_mission_metadata()
    if md and mission_id in md:
        tags.update(_tags_from_metadata(md[mission_id]))
    for b in bonus_objective_ids or []:
        if b == BONUS_GRID:
            tags.add("bonus_grid")
        elif b == BONUS_MECHS:
            tags.add("bonus_mechs")
        elif b == BONUS_KILL_FIVE:
            tags.add("bonus_kill_five")
        elif b == BONUS_DEBRIS:
            tags.add("bonus_debris")
        elif b == BONUS_SELFDAMAGE:
            tags.add("bonus_selfdamage")
        elif b == BONUS_PACIFIST:
            tags.add("bonus_pacifist")
        elif b == BONUS_BLOCK:
            tags.add("bonus_block")
        elif b == BONUS_ASSET:
            tags.add("bonus_asset")
    return tags


def _bonus_value(bonus_id: int, grid_power: int) -> tuple[int, str]:
    """Reward score + label for a single bonus objective."""
    sym = BONUS_SYMBOL.get(bonus_id, "·")
    if bonus_id == BONUS_GRID:
        if grid_power < 5:
            return 4, f"⚡ grid bonus + low grid ({grid_power}) → defensive"
        return 2, f"⚡ grid bonus (grid {grid_power})"
    if bonus_id == BONUS_MECHS:
        return 4, f"{sym} keep mechs alive"
    if bonus_id == BONUS_KILL_FIVE:
        return 2, f"{sym} kill 7 enemies"
    if bonus_id == BONUS_DEBRIS:
        return 2, f"{sym} destroy 5 debris"
    if bonus_id == BONUS_SELFDAMAGE:
        return 2, f"{sym} no self-damage"
    if bonus_id == BONUS_PACIFIST:
        return 2, f"{sym} kill-limit / pacifist"
    if bonus_id == BONUS_BLOCK:
        return 2, f"{sym} block emergence"
    if bonus_id == BONUS_ASSET:
        return 5, f"{sym} pilot/asset reward"
    return 1, f"bonus#{bonus_id}"


def _apply_lightning_war_routing(
    entry: dict[str, Any],
    mission_tags: set[str],
    score: int,
    rationale: list[str],
) -> int:
    """Bias mission choice for Blitzkrieg's under-30-minute achievement.

    Lightning War does not care about perfect islands or bonus objectives.
    The route picker should therefore prefer short, low-friction missions
    over reputation. These modifiers are deliberately large enough to beat
    the normal Perfect-Island farming penalties when a mission is known fast.
    """
    mission_id = entry.get("mission_id", "")
    bonus_ids = entry.get("bonus_objective_ids", []) or []
    delta = 0

    if "train" in mission_tags:
        delta -= 70
        rationale.append(
            "-70 Lightning War: protected train objective can stall fast runs"
        )
    if "env_tidal" in mission_tags and mission_id != "Mission_Terratide":
        delta += 25
        rationale.append("+25 Lightning War: fast Tidal Waves mission")
    if mission_id == "Mission_Terratide":
        delta -= 45
        rationale.append("-45 Lightning War: Terratide/Sandstorm animation drag")
    if "env_cataclysm" in mission_tags:
        delta -= 10
        rationale.append(
            "-10 Lightning War: Cataclysm/Seismic animations measured slow"
        )
    if "defensive_smoke" in mission_tags or mission_id == "Mission_Sandstorm":
        delta -= 10
        rationale.append("-10 Lightning War: Sandstorm animations measured slow")
    if (
        "four_turn" in mission_tags
        and not (
            {"train", "env_tidal", "env_cataclysm", "defensive_smoke"}
            & mission_tags
        )
    ):
        delta += 20
        rationale.append("+20 Lightning War: metadata 4-turn mission")
    if mission_id == "Mission_Battle":
        delta += 8
        rationale.append("+8  Lightning War: plain battle has low UI friction")

    if mission_id == "Mission_Bomb":
        delta -= 70
        rationale.append(
            "-70 Lightning War: Renfield Bombs causes web/objective drift and "
            "slow final turns"
        )

    if mission_id == "Mission_Satellite":
        delta -= 45
        rationale.append(
            "-45 Lightning War: Satellite Launches is avoid-unless-forced"
        )
    if "bad_repairs" in mission_tags or "repair_platforms" in mission_tags:
        delta -= 70
        rationale.append(
            "-70 Lightning War: Bad Repairs / repair platforms are too slow"
        )
    if mission_id == "Mission_Trapped":
        delta -= 70
        rationale.append(
            "-70 Lightning War: Power Generator trap can force mech damage"
        )
    if mission_id == "Mission_Force":
        delta -= 70
        rationale.append(
            "-70 Lightning War: mountain counter is slow and can force mech damage"
        )
    if mission_id == "Mission_AcidStorm":
        delta -= 12
        rationale.append(
            "-12 Lightning War: Acid Storm can add ACID cleanup friction"
        )

    detritus_speed_traps = {
        "Mission_AcidTank",
        "Mission_Barrels",
        "Mission_Disposal",
    }
    if mission_id in detritus_speed_traps:
        delta -= 45
        rationale.append(
            f"-45 Lightning War: Detritus vats/barrels UI-combat drag ({mission_id})"
        )

    slow_mission_ids = {
        "Mission_Artillery",
        "Mission_AcidStorm",
        "Mission_Crack",
        "Mission_Dam",
        "Mission_ForestFire",
        "Mission_FreezeBldg",
        "Mission_Holes",
        "Mission_Mines",
        "Mission_Power",
        "Mission_Solar",
        "Mission_Survive",
        "Mission_Tanks",
        "Mission_Teleporter",
        "Mission_Terraform",
        "Mission_Volatile",
        "Mission_Wind",
    }
    if mission_id in slow_mission_ids:
        delta -= 28
        rationale.append(f"-28 Lightning War: slow/fragile objective ({mission_id})")

    very_slow_mission_ids = {
        "Mission_Artillery",
        "Mission_Mines",
    }
    if mission_id in very_slow_mission_ids:
        delta -= 25
        rationale.append(
            f"-25 Lightning War: measured slow mission/template ({mission_id})"
        )
    if mission_id == "Mission_ForestFire":
        delta -= 35
        rationale.append(
            "-35 Lightning War: Forest Fire post-enemy/classifier friction"
        )

    slow_tags = {
        "fire_tile_counter",
        "fragile_ally_objective",
        "mite_counter",
        "protect_specific_building",
        "terraform_grass_counter",
        "volatile_vek",
    }
    fired_slow_tags = sorted(mission_tags & slow_tags)
    if fired_slow_tags:
        delta -= 12
        rationale.append(
            "-12 Lightning War: objective/review friction "
            f"({', '.join(fired_slow_tags)})"
        )

    if BONUS_ASSET in bonus_ids:
        delta -= 20
        rationale.append("-20 Lightning War: asset/pod reward adds UI time")
    if BONUS_KILL_FIVE in bonus_ids:
        delta -= 5
        rationale.append("-5  Lightning War: kill-count bonus invites overplay")
    if BONUS_PACIFIST in bonus_ids:
        delta -= 5
        rationale.append("-5  Lightning War: kill-limit bonus invites review")

    return score + delta


def _apply_lightning_baseline_routing(
    entry: dict[str, Any],
    mission_tags: set[str],
    score: int,
    rationale: list[str],
) -> tuple[int, str | None]:
    """Conservative Lightning route policy for no-surprise baseline proofs."""
    mission_id = entry.get("mission_id", "")
    delta = 0
    veto_reason = None

    if "train" in mission_tags:
        delta -= 80
        veto_reason = "baseline_reliability_veto:train"
        rationale.append(
            "-80 Lightning baseline: train objective can fail after clean turns"
        )
    if mission_id == "Mission_Battle":
        delta += 8
        rationale.append("+8  Lightning baseline: plain battle has low UI friction")
    if "env_tidal" in mission_tags:
        delta -= 70
        veto_reason = "baseline_reliability_veto:tides"
        rationale.append(
            "-70 Lightning baseline: Tidal Waves can trap Blitzkrieg into "
            "final-turn mech/objective losses"
        )
    if "four_turn" in mission_tags and "train" not in mission_tags:
        delta += 6
        rationale.append("+6  Lightning baseline: metadata 4-turn mission")

    fragile_tags = {
        "fire_tile_counter",
        "fragile_ally_objective",
        "mite_counter",
        "protect_specific_building",
        "terraform_grass_counter",
        "volatile_vek",
    }
    fired_fragile_tags = sorted(mission_tags & fragile_tags)
    if fired_fragile_tags:
        delta -= 20
        rationale.append(
            "-20 Lightning baseline: fragile objective/review tags "
            f"({', '.join(fired_fragile_tags)})"
        )

    return score + delta, veto_reason


def _apply_no_survivors_routing(
    entry: dict[str, Any],
    mission_tags: set[str],
    squad_tags: set[str],
    grid_power: int,
    score: int,
    rationale: list[str],
) -> int:
    """Route toward dense, low-friction seven-death setups."""
    mission_id = entry.get("mission_id", "")
    bonus_ids = entry.get("bonus_objective_ids", []) or []
    delta = 0

    if "walking_bomb_deploy" in squad_tags:
        delta += 6
        rationale.append("+6  No Survivors: Walking Bomb setup weapon online")
    if mission_id == "Mission_Battle":
        delta += 10
        rationale.append("+10 No Survivors: plain battle has low objective friction")
    if BONUS_KILL_FIVE in bonus_ids:
        delta += 35
        rationale.append(
            "+35 No Survivors: kill-count objective implies dense enemy board"
        )

    death_env_tags = {
        "env_acid",
        "env_cataclysm",
        "env_lava",
        "env_lightning",
    }
    fired_death_env_tags = sorted(mission_tags & death_env_tags)
    if fired_death_env_tags:
        delta += 14
        rationale.append(
            "+14 No Survivors: environment can contribute unit deaths "
            f"({', '.join(fired_death_env_tags)})"
        )
    if "high_threat" in mission_tags and grid_power >= 5:
        delta += 8
        rationale.append("+8  No Survivors: high-threat board can add enemy bodies")
    if "boss" in mission_tags and grid_power >= 5:
        delta += 6
        rationale.append("+6  No Survivors: boss mission likely increases density")
    if "infinite_spawn" in mission_tags and grid_power >= 5:
        delta += 5
        rationale.append("+5  No Survivors: infinite spawns can refill bodies")

    if "train" in mission_tags:
        delta -= 70
        rationale.append(
            "-70 No Survivors: train objective is protected-objective friction"
        )

    fragile_tags = {
        "bad_repairs",
        "fire_tile_counter",
        "fragile_ally_objective",
        "mite_counter",
        "protect_specific_building",
        "repair_platforms",
        "terraform_grass_counter",
        "volatile_vek",
    }
    fired_fragile_tags = sorted(mission_tags & fragile_tags)
    if fired_fragile_tags:
        delta -= 35
        rationale.append(
            "-35 No Survivors: fragile/protected objective friction "
            f"({', '.join(fired_fragile_tags)})"
        )

    slow_or_protected_mission_ids = {
        "Mission_Bomb",
        "Mission_Dam",
        "Mission_ForestFire",
        "Mission_Holes",
        "Mission_Power",
        "Mission_Repair",
        "Mission_Satellite",
        "Mission_Solar",
        "Mission_Tanks",
        "Mission_Teleporter",
        "Mission_Terraform",
        "Mission_Trapped",
        "Mission_Wind",
    }
    if mission_id in slow_or_protected_mission_ids:
        delta -= 20
        rationale.append(
            f"-20 No Survivors: route avoids protected/slow mission ({mission_id})"
        )

    if BONUS_PACIFIST in bonus_ids:
        delta -= 35
        rationale.append("-35 No Survivors: kill-limit objective fights the target")
    if BONUS_BLOCK in bonus_ids:
        delta -= 12
        rationale.append("-12 No Survivors: spawn-block bonus can reduce body count")
    if BONUS_ASSET in bonus_ids:
        delta -= 10
        rationale.append("-10 No Survivors: asset objective adds protection burden")

    return score + delta


_UNAVAILABLE_BOOL_FIELDS = {
    "active",
    "completed",
    "current",
    "hover_preview",
    "hovered",
    "in_progress",
    "is_active",
    "is_completed",
    "is_current",
    "is_overrun",
    "overrun",
    "preview",
    "stale",
}
_UNAVAILABLE_STATE_VALUES = {
    "active",
    "combat",
    "completed",
    "current",
    "done",
    "hover",
    "hover_preview",
    "in_progress",
    "overrun",
    "preview",
    "running",
    "stale",
}


def _unavailable_mission_reason(entry: dict[str, Any]) -> str | None:
    """Return why a bridge island-map entry should not be rankable.

    The Lua bridge normally emits only available island choices, but stale
    reads from hover previews, completed regions, or pause-menu leakage can
    carry the same mission-shaped payload. Prefer dropping explicitly marked
    non-options over letting them outrank real island choices.
    """
    if entry.get("available") is False or entry.get("is_available") is False:
        return "available=false"
    for field in sorted(_UNAVAILABLE_BOOL_FIELDS):
        if entry.get(field) is True:
            return field
    for field in ("state", "status", "mission_state", "availability"):
        value = entry.get(field)
        if value is None:
            continue
        normalized = str(value).strip().lower().replace("-", "_").replace(" ", "_")
        if normalized in _UNAVAILABLE_STATE_VALUES:
            return f"{field}={value}"
    return None


def score_mission(
    entry: dict[str, Any],
    squad_tags: set[str],
    grid_power: int,
    mission_metadata: dict[str, dict[str, Any]] | None = None,
    routing: str = "default",
) -> dict[str, Any]:
    """Score one ``island_map`` entry against the squad.

    Returns the input entry augmented with ``score`` and
    ``rationale_lines`` (a list of strings — first line per bonus
    award, then per fired penalty).

    ``mission_metadata`` defaults to the cached
    ``data/mission_metadata.json`` payload; tests pass a synthetic
    overlay so they're not flaky on game updates.
    """
    mission_id = entry.get("mission_id", "")
    bonus_ids = entry.get("bonus_objective_ids", []) or []
    env = entry.get("environment")
    diff_mod = entry.get("diff_mod", 0) or 0

    mission_tags = derive_mission_tags(mission_id, bonus_ids, env, mission_metadata)
    rationale: list[str] = []
    score = 0

    # Star bonuses + ⚡ rewards.
    for b in bonus_ids:
        v, label = _bonus_value(b, grid_power)
        score += v
        rationale.append(f"+{v}  {label}")
    # Two-star double bonus (rare; some missions stack).
    if len(bonus_ids) >= 2:
        score += 2
        rationale.append("+2  ★★ double-bonus mission")
    # Perfect Island farming needs every bonus objective, not just grid
    # safety. These counters require special turn-by-turn planning that the
    # tactical solver does not hard-gate yet, so strongly prefer other slate
    # options whenever they exist.
    if BONUS_BLOCK in bonus_ids:
        score -= 12
        rationale.append("-12 block-spawn objective risky for Perfect Island farming")
    if BONUS_PACIFIST in bonus_ids:
        score -= 12
        rationale.append("-12 kill-limit objective risky for Perfect Island farming")
    if "fire_tile_counter" in mission_tags:
        score -= 50
        rationale.append(
            "-50 fire-tile counter objective not solver-gated — hard veto"
        )
    if "fragile_ally_objective" in mission_tags:
        score -= 20
        rationale.append("-20 fragile ally objective risky for Perfect Island farming")
    if "terraform_grass_counter" in mission_tags:
        score -= 50
        rationale.append(
            "-50 terraform-grass counter objective not fully solver-gated — hard veto"
        )
    if "mite_counter" in mission_tags:
        score -= 50
        rationale.append(
            "-50 mite counter objective not fully solver-gated — hard veto"
        )
    if "cataclysm_chasm" in squad_tags:
        if mission_id == "Mission_Trapped":
            score -= 35
            rationale.append(
                "-35 Cataclysm Core: Power Generator trap has poor pit payoff "
                "and can force objective-loss gates"
            )
        if "earth_mover_pit" in mission_tags:
            score += 12
            rationale.append(
                "+12 Cataclysm Core: Earth Mover pit creates throw/drop lines"
            )
        if "env_cataclysm" in mission_tags:
            score += 8
            rationale.append(
                "+8  Cataclysm Core: falling terrain creates more chasms"
            )

    # Penalties: squad/mission mismatch.
    if "train" in mission_tags and "train_defender" not in squad_tags:
        score -= 8
        rationale.append("-8  train mission, no train_defender in squad")
    # High-threat scaling. The flat -5 below grid-5 underweighted the
    # actual cliff: at grid≤2 a high-threat mission has been the proximate
    # cause of every recent timeline loss (Pinnacle 2026-04-27 District
    # Z-1101 dropped grid 4→0 in two turns; squad had no per-turn DPS
    # ceiling against escalating Mission_Infinite spawns). Steeper curve:
    #   grid==4: -8   (current bonus values cap at +6, so a -8 only loses
    #                   if the mission has no ★★⚡ stack worth pushing
    #                   into a 4-grid risk)
    #   grid==3: -15  (effectively veto unless every alternative is worse)
    #   grid≤2:  -50  (hard veto — never picked when any non-high-threat
    #                   mission is on the map)
    # The previous -5 stays as the no-margin grid-4-to-5 floor for
    # callers who shimmed in a mid-island map without grid context.
    if "high_threat" in mission_tags:
        if grid_power <= 2:
            score -= 50
            rationale.append(f"-50 high-threat + critical grid ({grid_power}) — hard veto")
        elif grid_power == 3:
            score -= 15
            rationale.append(f"-15 high-threat + grid {grid_power} (severe penalty)")
        elif grid_power == 4:
            score -= 8
            rationale.append(f"-8  high-threat + grid {grid_power} (low margin)")
        elif grid_power < 5:
            score -= 5
            rationale.append(f"-5  high-threat + low grid ({grid_power})")
    if "volatile_vek" in mission_tags and "crowd_control" not in squad_tags:
        score -= 3
        rationale.append("-3  volatile-Vek mission, no crowd-control in squad")
    if "env_tidal" in mission_tags and "flying" not in squad_tags:
        score -= 2
        rationale.append("-2  Tidal Waves env, no flying mech")
    if "env_cataclysm" in mission_tags and "flying" not in squad_tags:
        score -= 2
        rationale.append("-2  Cataclysm/Seismic env, no flying mech")
    if "env_lightning" in mission_tags and grid_power < 4:
        score -= 3
        rationale.append(f"-3  Lightning/AirStrike env + grid {grid_power}")
    if "conveyor" in mission_tags and grid_power < 4:
        score -= 2
        rationale.append(f"-2  conveyor mission + low grid ({grid_power})")
    # Infinite-spawn missions (descendants of Mission_Infinite — ~93% of
    # templates including Mission_Volatile, Mission_Survive, every
    # *Boss* mission, most environment missions). Each turn brings a
    # fresh wave (Mission:GetSpawnCount → SpawnsPerTurn), so the mission
    # bleeds grid even when won. At low grid the next-mission cliff is
    # what kills timelines (run 20260425_185532_218: m07 Mission_Barrels
    # drained 4→2, then m08 Mission_Teleporter and m13 Mission_BlobBoss
    # both entered at grid 2 with no margin).
    #
    # Rationale for thresholds:
    #   grid==3: -10 → Volatile-style mission with BONUS_MECHS (+4) lands
    #     at -6, losing to a Mission_Battle-style 1★ alternative (+1, no
    #     infinite_spawn → no penalty) by 7 points. Still pickable when
    #     no fixed-roster alternative exists.
    #   grid≤2: -50 → hard veto, matching high_threat semantics. At this
    #     grid the next mission decides the run; only Mission_Battle /
    #     Mission_Reactivation / Mission_Respawn-style missions stay
    #     viable.
    # Subsumes the ``boss + grid<4`` -4 penalty (every boss mission is
    # also infinite_spawn, and -10/-50 dominates -4): use elif so we
    # don't double-charge.
    if "infinite_spawn" in mission_tags and grid_power <= 2:
        score -= 50
        rationale.append(
            f"-50 infinite-spawn + critical grid ({grid_power}) — hard veto"
        )
    elif "infinite_spawn" in mission_tags and grid_power == 3:
        score -= 10
        rationale.append(
            f"-10 infinite-spawn + grid {grid_power} (next-mission cliff)"
        )
    elif "boss" in mission_tags and grid_power < 4:
        score -= 4
        rationale.append(f"-4  boss + low grid ({grid_power})")
    if "protect_specific_building" in mission_tags and "crowd_control" not in squad_tags:
        score -= 2
        rationale.append("-2  protect-specific + no crowd-control")

    # Enemy-class mismatches (driven by mission_metadata.forced_pawns).
    # These fire only when the mission *guarantees* the type — bosses
    # and forced spawns. Procedural rosters are not statically known.
    if "flier_heavy" in mission_tags and (
        "armor_pierce" not in squad_tags and "aoe" not in squad_tags
    ):
        score -= 3
        rationale.append("-3  flying-heavy spawn pool + no armor-pierce / no AoE")
    if "armored_heavy" in mission_tags and "armor_pierce" not in squad_tags:
        score -= 4
        rationale.append("-4  armored-heavy spawn pool + no armor-pierce")
    if "psion_present" in mission_tags and "burst" not in squad_tags:
        score -= 2
        rationale.append("-2  psion (Jelly leader) present + no burst")

    # Difficulty modifier (set in createIncidents:302).
    if diff_mod == 1:  # DIFF_MOD_HARD
        score -= 1
        rationale.append("-1  marked HARD by engine")
    elif diff_mod == -1:  # DIFF_MOD_EASY
        score += 1
        rationale.append("+1  marked EASY by engine")

    route_auto_start_veto_reason = None
    if routing == "lightning_war":
        score = _apply_lightning_war_routing(
            entry, mission_tags, score, rationale
        )
    elif routing == "lightning_baseline":
        score, route_auto_start_veto_reason = _apply_lightning_baseline_routing(
            entry, mission_tags, score, rationale
        )
    elif routing == "no_survivors":
        score = _apply_no_survivors_routing(
            entry, mission_tags, squad_tags, grid_power, score, rationale
        )
    elif routing != "default":
        raise ValueError(f"unknown mission routing mode: {routing}")

    out = dict(entry)
    out["score"] = score
    out["mission_tags"] = sorted(mission_tags)
    out["rationale_lines"] = rationale
    if route_auto_start_veto_reason is not None:
        out["route_auto_start_veto_reason"] = route_auto_start_veto_reason
    return out


def score_island_map(
    island_map: list[dict[str, Any]] | None,
    squad_units: list[dict[str, Any]],
    grid_power: int,
    mission_metadata: dict[str, dict[str, Any]] | None = None,
    routing: str = "default",
) -> list[dict[str, Any]]:
    """Score every entry of an island_map; return descending by score.

    ``island_map`` may be None or empty (combat / between-states); this
    returns []. ``squad_units`` is the bridge units list. ``grid_power``
    is the current ⚡ count (used for the low-grid weighting).
    ``mission_metadata`` defaults to the cached
    ``data/mission_metadata.json``; pass a synthetic dict in tests.
    """
    if not island_map:
        return []
    squad_tags = derive_squad_tags(squad_units)
    scored = []
    for e in island_map:
        if _unavailable_mission_reason(e):
            continue
        scored.append(
            score_mission(e, squad_tags, grid_power, mission_metadata, routing)
        )
    scored.sort(key=lambda e: e["score"], reverse=True)
    return scored
