"""Self-healing loop — novelty detector for pawn types, terrain,
weapons, and screens.

Cross-references a live ``Board`` (plus bridge phase string) against
``data/known_types.json`` and reports anything we've never cataloged.
Run by ``cmd_read`` and ``cmd_solve``; the result surfaces as
``result["unknowns"]`` and trips the research gate so the operator (or
Phase 1 detector) can resolve the unknown before it drives a desync.

Per ``docs/self_healing_loop_design.md``: this is pure instrumentation
on the detector side. The gate itself lives in
``src/solver/research_gate.py`` and the protocol in CLAUDE.md rule 20.

The known baseline is generated by ``scripts/regenerate_known_types.py``
from four sources: Fandom wiki filenames, Rust ``WId``/``Terrain`` enums,
pawn types observed in existing recordings, and the bridge/save-parser
phase strings known to the codebase.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parent.parent.parent
_KNOWN_TYPES_PATH = _REPO / "data" / "known_types.json"

_CACHE: dict | None = None


def _normalize_weapon(w: str) -> str:
    """Strip underscores so bridge form (``Prime_Punchmech``) matches
    the Rust ``WId`` enum variant (``PrimePunchmech``).

    Both forms are commonly seen: bridge JSON and mech loadouts use
    underscores; the Rust enum and the scanner extract no-underscore.
    """
    return w.replace("_", "")


def _load_known() -> dict:
    """Load and cache ``data/known_types.json``. Returns empty sets on miss."""
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    if not _KNOWN_TYPES_PATH.is_file():
        _CACHE = {
            "pawn_types": set(),
            "terrain_ids": set(),
            "weapons": set(),
            "phases": set(),
        }
        return _CACHE
    try:
        with open(_KNOWN_TYPES_PATH) as f:
            doc = json.load(f)
    except (json.JSONDecodeError, OSError):
        _CACHE = {
            "pawn_types": set(),
            "terrain_ids": set(),
            "weapons": set(),
            "phases": set(),
        }
        return _CACHE

    # Merge wiki + observed into the live "known pawn types" set.
    # Wiki names (``Firefly``) and bridge types (``Firefly1``) don't match
    # verbatim — observed is what gets matched at runtime, wiki is the
    # authoritative taxonomy we'll reconcile to in Phase 1.
    pawn_set: set[str] = set()
    pawn_set.update(doc.get("wiki_pages", []))
    pawn_set.update(doc.get("observed_pawn_types", []))

    terrain_set: set[str] = set()
    terrain_set.update(doc.get("terrain_ids", []))
    terrain_set.update(t.lower() for t in doc.get("terrain_enum", []))

    # Weapons: Rust enum (no-underscore) + bridge-observed (underscored).
    # At comparison time we also try the normalized form — see
    # detect_unknowns below.
    weapon_set: set[str] = set()
    weapon_set.update(doc.get("weapon_enum", []))
    weapon_set.update(doc.get("observed_weapons", []))

    phase_set: set[str] = set()
    phase_set.update(doc.get("known_phases", []))

    _CACHE = {
        "pawn_types": pawn_set,
        "terrain_ids": terrain_set,
        "weapons": weapon_set,
        "phases": phase_set,
    }
    return _CACHE


def reset_cache() -> None:
    """Drop the cached known-types doc. Used by tests that rewrite the file."""
    global _CACHE
    _CACHE = None


def detect_unknowns(board: Any, phase: str | None = None) -> dict:
    """Return novel pawn types, terrain ids, weapons, and screens.

    Args:
        board: ``src.model.board.Board`` instance (or anything with
            ``.units`` and ``.tiles[x][y].terrain``).
        phase: Bridge/save-parser phase string (e.g. ``combat_player``).
            None skips the screen check.

    Returns:
        ``{"types": [...], "terrain_ids": [...], "weapons": [...], "screens": [...]}``
        — sorted, de-duped, each flagged string appearing on ``board``
        (or in the passed ``phase``) and absent from the known-types
        baseline. All four lists empty when nothing is novel.
    """
    known = _load_known()

    novel_types: set[str] = set()
    novel_weapons: set[str] = set()
    for u in getattr(board, "units", []) or []:
        t = getattr(u, "type", None)
        if t and t not in known["pawn_types"]:
            novel_types.add(t)
        # Check primary + secondary weapon slots. Passives live in the
        # bridge ``weapons`` list but not on ``.weapon`` / ``.weapon2``,
        # so they're out of scope here — extend when passive novelty
        # becomes a real failure mode.
        for w in (getattr(u, "weapon", ""), getattr(u, "weapon2", "")):
            if not w:
                continue
            if w in known["weapons"]:
                continue
            if _normalize_weapon(w) in known["weapons"]:
                continue
            novel_weapons.add(w)

    novel_terrain: set[str] = set()
    tiles = getattr(board, "tiles", None)
    if tiles is not None:
        for x in range(8):
            for y in range(8):
                try:
                    tile = tiles[x][y]
                except (IndexError, KeyError, TypeError):
                    continue
                terrain = getattr(tile, "terrain", None)
                if terrain and terrain not in known["terrain_ids"]:
                    novel_terrain.add(terrain)

    novel_screens: list[str] = []
    if phase is not None and phase and phase not in known["phases"]:
        novel_screens.append(phase)

    return {
        "types": sorted(novel_types),
        "terrain_ids": sorted(novel_terrain),
        "weapons": sorted(novel_weapons),
        "screens": novel_screens,
    }
