"""Self-healing loop — novelty detector for pawn types and terrain.

Cross-references a live ``Board`` against ``data/known_types.json`` and
reports any ``unit.type`` string or terrain id we've never cataloged.
Run by ``cmd_read``; the result surfaces as ``result["unknowns"]`` so the
operator (or Phase 1 detector) can queue research before the unknown
drives a desync.

Per ``docs/self_healing_loop_design.md``: this is pure instrumentation.
Flagging a type does not change solver behavior in Phase 0.

The known baseline is generated by ``scripts/regenerate_known_types.py``
from three sources: Fandom wiki filenames, Rust ``WId``/``Terrain`` enums,
and pawn types observed in existing recordings.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parent.parent.parent
_KNOWN_TYPES_PATH = _REPO / "data" / "known_types.json"

_CACHE: dict | None = None


def _load_known() -> dict:
    """Load and cache ``data/known_types.json``. Returns empty sets on miss."""
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    if not _KNOWN_TYPES_PATH.is_file():
        _CACHE = {"pawn_types": set(), "terrain_ids": set()}
        return _CACHE
    try:
        with open(_KNOWN_TYPES_PATH) as f:
            doc = json.load(f)
    except (json.JSONDecodeError, OSError):
        _CACHE = {"pawn_types": set(), "terrain_ids": set()}
        return _CACHE

    # Merge wiki + observed into the live "known pawn types" set.
    # Wiki names (``Firefly``) and bridge types (``Firefly1``) don't match
    # verbatim — observed is what gets matched at runtime, wiki is the
    # authoritative taxonomy we'll reconcile to in Phase 1.
    pawn_set: set[str] = set()
    pawn_set.update(doc.get("wiki_pages", []))
    pawn_set.update(doc.get("observed_pawn_types", []))

    terrain_set: set[str] = set()
    terrain_set.update(doc.get("terrain_ids", []))
    terrain_set.update(t.lower() for t in doc.get("terrain_enum", []))

    _CACHE = {"pawn_types": pawn_set, "terrain_ids": terrain_set}
    return _CACHE


def reset_cache() -> None:
    """Drop the cached known-types doc. Used by tests that rewrite the file."""
    global _CACHE
    _CACHE = None


def detect_unknowns(board: Any) -> dict:
    """Return novel pawn types and terrain ids present on ``board``.

    Args:
        board: ``src.model.board.Board`` instance (or anything with
            ``.units`` and ``.tiles[x][y].terrain``).

    Returns:
        ``{"types": [...], "terrain_ids": [...]}`` — sorted, de-duped,
        each flagged string appearing on ``board`` and absent from the
        known-types baseline. Both lists empty when nothing is novel.
    """
    known = _load_known()

    novel_types: set[str] = set()
    for u in getattr(board, "units", []) or []:
        t = getattr(u, "type", None)
        if t and t not in known["pawn_types"]:
            novel_types.add(t)

    novel_terrain: set[str] = set()
    tiles = getattr(board, "tiles", None)
    if tiles is not None:
        for x in range(8):
            for y in range(8):
                try:
                    tile = tiles[x][y]
                except (IndexError, KeyError, TypeError):
                    continue
                terrain = getattr(tile, "terrain", None)
                if terrain and terrain not in known["terrain_ids"]:
                    novel_terrain.add(terrain)

    return {
        "types": sorted(novel_types),
        "terrain_ids": sorted(novel_terrain),
    }
