#!/usr/bin/env python3
"""Offline S0 path-rule/solver connection; never reads or operates a live game."""

from __future__ import annotations

import argparse
import hashlib
import importlib
from importlib.machinery import EXTENSION_SUFFIXES
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.observatory.path_cost_ordering import validate_path_cost_ordering_map
from src.solver.evidence_reconciliation import build_movement_index, canonical_sha256, verify_ledger
from src.solver.observation_contract import encode_observation, load_contract


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def loaded_extension_path(solver) -> Path:
    """Hash the module implementing solve, never an arbitrary neighboring DLL."""
    path = Path(importlib.import_module(solver.solve.__module__).__file__)
    if not path.is_file() or not any(str(path).endswith(suffix) for suffix in EXTENSION_SUFFIXES):
        raise ValueError("solver entry point is not bound to a loaded extension")
    return path


def parser_inventory() -> dict[str, set[str]]:
    """Read this crate's simple field declarations, including serde wire names.

    Aliases are classified too; changing the parser requires re-auditing the
    contract rather than automatically admitting a new field.
    """
    source = (ROOT / "rust_solver/src/serde_bridge.rs").read_text(encoding="utf-8")
    inventory = {}
    for scope in ("JsonInput", "JsonTile", "JsonUnit"):
        body = re.search(r"pub struct " + scope + r" \{(.*?)\n\}", source, re.S).group(1)
        fields = set()
        attributes = []
        for line in body.splitlines():
            if line.strip().startswith("#[serde("):
                attributes.append(line)
            match = re.match(r"\s*pub (\w+):", line)
            if match:
                names = " ".join(attributes)
                rename = re.search(r'rename = "([^"]+)"', names)
                fields.add(rename.group(1) if rename else match.group(1))
                fields.update(re.findall(r'alias = "([^"]+)"', names))
                attributes = []
        inventory[scope] = fields
    return inventory


def verify_inventory() -> dict:
    contract = load_contract()
    inventory = parser_inventory()
    extras = set(contract["synthetic_oracle_keys"])
    for scope, names in inventory.items():
        declared = set(contract["fields"][scope])
        expected = names | (extras if scope == "JsonInput" else set())
        if declared != expected:
            raise ValueError(f"{scope} audit drift: missing={expected-declared}, stale={declared-expected}")
    return {scope: len(names) for scope, names in inventory.items()}


def corridor(massive: bool, speed: int) -> dict:
    return {
        "grid_power": 7, "grid_power_max": 7, "turn": 1, "total_turns": 4,
        "spawning_tiles": [],
        "tiles": [{"x": x, "y": y, "terrain":
                   ("water" if y == 1 else "ground") if x == 0 and y <= 3 else "mountain"}
                  for x in range(8) for y in range(8)],
        "units": [{"uid": 0, "type": "CombatMech", "x": 0, "y": 0,
                   "hp": 3, "max_hp": 3, "team": 1, "mech": True,
                   "move": speed, "massive": massive, "flying": False,
                   "active": True, "can_move": True, "weapons": []}],
    }


def run(executable: Path) -> dict:
    import itb_solver

    counts = verify_inventory()
    movement_index = build_movement_index(ROOT)
    ledger_verification = verify_ledger(ROOT, executable)
    evidence_path = ROOT / "data/observatory/native/windows_build_13725832_31fe35265598_path_cost_ordering.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    native = validate_path_cost_ordering_map(executable, evidence)
    # Expectations are handwritten consequences of the independently reviewed
    # native terrain/profile and unit-cost laws, not generated by Rust.
    variants = [(False, 2, {(0, 0)}), (True, 1, {(0, 0), (0, 1)}),
                (True, 2, {(0, 0), (0, 1), (0, 2)})]
    results = []
    mismatches = []
    observation_pairs = 0
    for massive, speed, expected in variants:
        state = corridor(massive, speed)
        clean = encode_observation(state)
        # Deliberately different privileged information must never change input.
        a = {**state, "rng_state": 1, "remaining_spawns": 0, "future_spawns": [[7, 7]]}
        b = {**state, "rng_state": 999, "remaining_spawns": 100, "future_spawns": [[1, 1]]}
        if not encode_observation(a) == encode_observation(b) == clean:
            raise ValueError("oracle pair changed planner input")
        observation_pairs += 1
        legal = []
        for x in range(8):
            for y in range(8):
                plan = [{"mech_uid": 0, "move_to": [x, y], "weapon_id": "None", "target": [x, y]}]
                replay = json.loads(itb_solver.replay_solution(clean, json.dumps(plan)))
                events = replay["action_results"][0]["events"]
                accepted = not any(e.startswith("illegal_move:") for e in events)
                moved = next(u for u in replay["predicted_states"][0]["post_move"]["units"] if u["uid"] == 0)
                if accepted:
                    legal.append([x, y])
                if accepted != ((x, y) in expected) or moved["pos"] != ([x, y] if accepted else [0, 0]):
                    mismatches.append({"massive": massive, "move": speed, "destination": [x, y],
                                       "events": events, "actual_position": moved["pos"]})
        results.append({"massive": massive, "move": speed, "attempted": 64,
                        "expected_legal": [list(p) for p in sorted(expected)], "replay_accepted": sorted(legal)})
    extension = loaded_extension_path(itb_solver)
    rust_source = {str(p.relative_to(ROOT)).replace("\\", "/"):
                   hashlib.sha256(p.read_bytes().replace(b"\r\n", b"\n")).hexdigest()
                   for p in sorted((ROOT / "rust_solver/src").glob("*.rs"))}
    rust_tree_sha256 = hashlib.sha256(json.dumps(rust_source, sort_keys=True).encode()).hexdigest()
    frontend_sources = {name: hashlib.sha256((ROOT / name).read_bytes().replace(b"\r\n", b"\n")).hexdigest()
                        for name in ("scripts/solver_first_s0.py", "src/solver/observation_contract.py",
                                     "src/solver/evidence_reconciliation.py")}
    return {
        "schema_version": 1, "milestone": "S0", "scenario": "ordinary_massive_water_corridor",
        "corpus_version": "s0-water-development-v1",
        "solver_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "simulator_version": itb_solver.simulator_version(), "extension_sha256": digest(extension),
        "information_mode": "provisional_player_observation_v1",
        "contract_sha256": digest(ROOT / "data/solver_first/s0_information_contract.json"),
        "tool_sha256": digest(Path(__file__)),
        "frontend_source_identity": {"hash_convention": "UTF-8 files with CRLF normalized to LF",
                                     "files": frontend_sources},
        "rust_source_identity": {"hash_convention": "UTF-8 files with CRLF normalized to LF",
                                 "tree_sha256": rust_tree_sha256, "files": rust_source},
        "parser_field_counts": counts, "original_build_sha256": evidence["identity"]["executable_sha256"],
        "path_evidence_sha256": digest(evidence_path), "path_source_reverification": native["status"],
        "evidence_class": "synthetic_scenario_against_original_static_rule_inference",
        "runtime_original_comparisons": 0, "attempted": 192, "mismatches": mismatches,
        "matched_original_trace_admitted": 0,
        "script_map_overlay_inventory_status": "not_consumed_by_executable_only_static_check; full-loop corpus pin still required",
        "oracle_observation_pairs": observation_pairs, "cases": results,
        "search_status": "not_evaluated", "held_out_status": "not_evaluated",
        "ledger_promotions": 0,
        "movement_index_canonical_sha256": canonical_sha256(movement_index),
        "ledger_reverification": ledger_verification,
        "remaining_blockers": ["matched original GetReachable output vectors",
                               "AddMove consumer, per-step effects, interruption and scheduler ordering",
                               "original full-turn ordered trace and next decision state",
                               "observation acquisition provenance for broader mission fields"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--executable", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--movement-index-output", type=Path)
    args = parser.parse_args()
    result = run(args.executable)
    if args.movement_index_output:
        with args.movement_index_output.open("x", encoding="utf-8", newline="\n") as out:
            json.dump(build_movement_index(ROOT), out, indent=2, sort_keys=True, allow_nan=False)
            out.write("\n")
    encoded = json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if args.output:
        with args.output.open("x", encoding="utf-8", newline="\n") as out:
            out.write(encoded)
    else:
        print(encoded, end="")
    return 1 if result["mismatches"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
